# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TestServiceProtoFile.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TestServiceProtoFile.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aTestServiceProtoFile.proto\"-\n\x07TestReq\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"I\n\x08TestResp\x12\x14\n\x0c\x63ompany_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65signation\x18\x02 \x01(\t\x12\x12\n\nsalary_eur\x18\x03 \x01(\x05\x32-\n\x07Testing\x12\"\n\x0bTestService\x12\x08.TestReq\x1a\t.TestRespb\x06proto3'
)




_TESTREQ = _descriptor.Descriptor(
  name='TestReq',
  full_name='TestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_name', full_name='TestReq.user_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='TestReq.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=75,
)


_TESTRESP = _descriptor.Descriptor(
  name='TestResp',
  full_name='TestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_name', full_name='TestResp.company_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='designation', full_name='TestResp.designation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='salary_eur', full_name='TestResp.salary_eur', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=150,
)

DESCRIPTOR.message_types_by_name['TestReq'] = _TESTREQ
DESCRIPTOR.message_types_by_name['TestResp'] = _TESTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestReq = _reflection.GeneratedProtocolMessageType('TestReq', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQ,
  '__module__' : 'TestServiceProtoFile_pb2'
  # @@protoc_insertion_point(class_scope:TestReq)
  })
_sym_db.RegisterMessage(TestReq)

TestResp = _reflection.GeneratedProtocolMessageType('TestResp', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESP,
  '__module__' : 'TestServiceProtoFile_pb2'
  # @@protoc_insertion_point(class_scope:TestResp)
  })
_sym_db.RegisterMessage(TestResp)



_TESTING = _descriptor.ServiceDescriptor(
  name='Testing',
  full_name='Testing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=152,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestService',
    full_name='Testing.TestService',
    index=0,
    containing_service=None,
    input_type=_TESTREQ,
    output_type=_TESTRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TESTING)

DESCRIPTOR.services_by_name['Testing'] = _TESTING

# @@protoc_insertion_point(module_scope)
